let survivor_perks = {
    "Ace in the Hole": {
        "url": "https://deadbydaylight.fandom.com/wiki/Ace_in_the_Hole",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/24/IconPerks_aceInTheHole.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 3,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 5
    },
    "Adrenaline": {
        "url": "https://deadbydaylight.fandom.com/wiki/Adrenaline",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f7/IconPerks_adrenaline.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 3,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 7
    },
    "Aftercare": {
        "url": "https://deadbydaylight.fandom.com/wiki/Aftercare",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0d/IconPerks_aftercare.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Alert": {
        "url": "https://deadbydaylight.fandom.com/wiki/Alert",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/71/IconPerks_alert.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 3
    },
    "Any Means Necessary": {
        "url": "https://deadbydaylight.fandom.com/wiki/Any_Means_Necessary",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/79/IconPerks_anyMeansNecessary.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 2
    },
    "Appraisal": {
        "url": "https://deadbydaylight.fandom.com/wiki/Appraisal",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c1/IconPerks_appraisal.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 3,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Autodidact": {
        "url": "https://deadbydaylight.fandom.com/wiki/Autodidact",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/96/IconPerks_autodidact.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 3
    },
    "Guardian": {
        "url": "https://deadbydaylight.fandom.com/wiki/Guardian",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/23/IconPerks_guardian.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 3,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 5
    },
    "Balanced Landing": {
        "url": "https://deadbydaylight.fandom.com/wiki/Balanced_Landing",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5e/IconPerks_balancedLanding.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 1,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 5
    },
    "Situational Awareness": {
        "url": "https://deadbydaylight.fandom.com/wiki/Situational_Awareness",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/02/IconPerks_betterTogether.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Bite the Bullet": {
        "url": "https://deadbydaylight.fandom.com/wiki/Bite_the_Bullet",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a5/IconPerks_biteTheBullet.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 1,
        "Total": 5
    },
    "Blast Mine": {
        "url": "https://deadbydaylight.fandom.com/wiki/Blast_Mine",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_blastMine.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Blood Pact": {
        "url": "https://deadbydaylight.fandom.com/wiki/Blood_Pact",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c9/IconPerks_bloodPact.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 3
    },
    "Boil Over": {
        "url": "https://deadbydaylight.fandom.com/wiki/Boil_Over",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_boilOver.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 2
    },
    "Bond": {
        "url": "https://deadbydaylight.fandom.com/wiki/Bond",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a0/IconPerks_bond.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Boon: Circle of Healing": {
        "url": "https://deadbydaylight.fandom.com/wiki/Boon:_Circle_of_Healing",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/54/IconPerks_boonCircleOfHealing.png",
        "Cleansing": 2,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 3,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 8
    },
    "Boon: Shadow Step": {
        "url": "https://deadbydaylight.fandom.com/wiki/Boon:_Shadow_Step",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c7/IconPerks_boonShadowStep.png",
        "Cleansing": 2,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 3,
        "Clutch": 0,
        "Total": 8
    },
    "Borrowed Time": {
        "url": "https://deadbydaylight.fandom.com/wiki/Borrowed_Time",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_borrowedTime.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 3,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 6
    },
    "Botany Knowledge": {
        "url": "https://deadbydaylight.fandom.com/wiki/Botany_Knowledge",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1e/IconPerks_botanyKnowledge.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 3,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Breakdown": {
        "url": "https://deadbydaylight.fandom.com/wiki/Breakdown",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_breakdown.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 2
    },
    "Breakout": {
        "url": "https://deadbydaylight.fandom.com/wiki/Breakout",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d0/IconPerks_breakout.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 6
    },
    "Buckle Up": {
        "url": "https://deadbydaylight.fandom.com/wiki/Buckle_Up",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/74/IconPerks_buckleUp.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Built to Last": {
        "url": "https://deadbydaylight.fandom.com/wiki/Built_to_Last",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3b/IconPerks_builtToLast.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 1,
        "Looping": 0,
        "Self-Sufficient": 3,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 5
    },
    "Calm Spirit": {
        "url": "https://deadbydaylight.fandom.com/wiki/Calm_Spirit",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/6c/IconPerks_calmSpirit.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 3,
        "Clutch": 0,
        "Total": 4
    },
    "Kinship": {
        "url": "https://deadbydaylight.fandom.com/wiki/Kinship",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1d/IconPerks_camaraderie.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Clairvoyance": {
        "url": "https://deadbydaylight.fandom.com/wiki/Clairvoyance",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/91/IconPerks_clairvoyance.png",
        "Cleansing": 1,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 1,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 7
    },
    "Counterforce": {
        "url": "https://deadbydaylight.fandom.com/wiki/Counterforce",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d1/IconPerks_counterforce.png",
        "Cleansing": 2,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Dance With Me": {
        "url": "https://deadbydaylight.fandom.com/wiki/Dance_With_Me",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_danceWithMe.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 2,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 1,
        "Total": 4
    },
    "Dark Sense": {
        "url": "https://deadbydaylight.fandom.com/wiki/Dark_Sense",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/92/IconPerks_darkSense.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Dead Hard": {
        "url": "https://deadbydaylight.fandom.com/wiki/Dead_Hard",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/75/IconPerks_deadHard.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Deception": {
        "url": "https://deadbydaylight.fandom.com/wiki/Deception",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/eb/IconPerks_deception.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 2,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 1,
        "Total": 4
    },
    "Decisive Strike": {
        "url": "https://deadbydaylight.fandom.com/wiki/Decisive_Strike",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_decisiveStrike.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 3,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 6
    },
    "Déjà Vu": {
        "url": "https://deadbydaylight.fandom.com/wiki/D%C3%A9j%C3%A0_Vu",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/89/IconPerks_dejaVu.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 2,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 5
    },
    "Deliverance": {
        "url": "https://deadbydaylight.fandom.com/wiki/Deliverance",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7e/IconPerks_deliverance.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 5
    },
    "Desperate Measures": {
        "url": "https://deadbydaylight.fandom.com/wiki/Desperate_Measures",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/84/IconPerks_desperateMeasures.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 2,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Detective's Hunch": {
        "url": "https://deadbydaylight.fandom.com/wiki/Detective%27s_Hunch",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPerks_detectivesHunch.png",
        "Cleansing": 1,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 1,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 8
    },
    "Distortion": {
        "url": "https://deadbydaylight.fandom.com/wiki/Distortion",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/41/IconPerks_distortion.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 3,
        "Clutch": 0,
        "Total": 3
    },
    "Diversion": {
        "url": "https://deadbydaylight.fandom.com/wiki/Diversion",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a6/IconPerks_diversion.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 2
    },
    "Empathy": {
        "url": "https://deadbydaylight.fandom.com/wiki/Empathy",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ae/IconPerks_empathy.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 6
    },
    "Fast Track": {
        "url": "https://deadbydaylight.fandom.com/wiki/Fast_Track",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/75/IconPerks_fastTrack.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 3,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 5
    },
    "Self-Aware": {
        "url": "https://deadbydaylight.fandom.com/wiki/Self-Aware",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_fixated.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 3
    },
    "Flashbang": {
        "url": "https://deadbydaylight.fandom.com/wiki/Flashbang",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/db/IconPerks_flashbang.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Flip-Flop": {
        "url": "https://deadbydaylight.fandom.com/wiki/Flip-Flop",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_flip-Flop.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 3
    },
    "For the People": {
        "url": "https://deadbydaylight.fandom.com/wiki/For_the_People",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_forThePeople.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 2,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 6
    },
    "Head On": {
        "url": "https://deadbydaylight.fandom.com/wiki/Head_On",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cb/IconPerks_headOn.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 5
    },
    "Hope": {
        "url": "https://deadbydaylight.fandom.com/wiki/Hope",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/18/IconPerks_hope.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 4
    },
    "Inner Healing": {
        "url": "https://deadbydaylight.fandom.com/wiki/Inner_Healing",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/df/IconPerks_innerHealing.png",
        "Cleansing": 1,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 3,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 6
    },
    "Iron Will": {
        "url": "https://deadbydaylight.fandom.com/wiki/Iron_Will",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_ironWill.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 2,
        "Self-Sufficient": 3,
        "Stealth": 3,
        "Clutch": 0,
        "Total": 8
    },
    "Kindred": {
        "url": "https://deadbydaylight.fandom.com/wiki/Kindred",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a8/IconPerks_kindred.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 3,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 6
    },
    "Leader": {
        "url": "https://deadbydaylight.fandom.com/wiki/Leader",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPerks_leader.png",
        "Cleansing": 1,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 5
    },
    "Left Behind": {
        "url": "https://deadbydaylight.fandom.com/wiki/Left_Behind",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c3/IconPerks_leftBehind.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 4
    },
    "Lightweight": {
        "url": "https://deadbydaylight.fandom.com/wiki/Lightweight",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/67/IconPerks_lightweight.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 3
    },
    "Lithe": {
        "url": "https://deadbydaylight.fandom.com/wiki/Lithe",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cc/IconPerks_lithe.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Lucky Break": {
        "url": "https://deadbydaylight.fandom.com/wiki/Lucky_Break",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a7/IconPerks_luckyBreak.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 3,
        "Clutch": 2,
        "Total": 6
    },
    "Mettle of Man": {
        "url": "https://deadbydaylight.fandom.com/wiki/Mettle_of_Man",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_mettleOfMan.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 1,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 4
    },
    "No Mither": {
        "url": "https://deadbydaylight.fandom.com/wiki/No_Mither",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f5/IconPerks_noMither.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 2
    },
    "No One Left Behind": {
        "url": "https://deadbydaylight.fandom.com/wiki/No_One_Left_Behind",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b0/IconPerks_noOneLeftBehind.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 4
    },
    "Object of Obsession": {
        "url": "https://deadbydaylight.fandom.com/wiki/Object_of_Obsession",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2b/IconPerks_objectOfObsession.png",
        "Cleansing": 1,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Off the Record": {
        "url": "https://deadbydaylight.fandom.com/wiki/Off_the_Record",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_offTheRecord.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 2,
        "Clutch": 1,
        "Total": 4
    },
    "Open-Handed": {
        "url": "https://deadbydaylight.fandom.com/wiki/Open-Handed",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/5d/IconPerks_open-Handed.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Pharmacy": {
        "url": "https://deadbydaylight.fandom.com/wiki/Pharmacy",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f1/IconPerks_pharmacy.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 2,
        "Looting": 3,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 5
    },
    "Plunderer's Instinct": {
        "url": "https://deadbydaylight.fandom.com/wiki/Plunderer%27s_Instinct",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/28/IconPerks_plunderersInstinct.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 3,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 6
    },
    "Poised": {
        "url": "https://deadbydaylight.fandom.com/wiki/Poised",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPerks_poised.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 3
    },
    "Power Struggle": {
        "url": "https://deadbydaylight.fandom.com/wiki/Power_Struggle",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4b/IconPerks_powerStruggle.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 4
    },
    "Premonition": {
        "url": "https://deadbydaylight.fandom.com/wiki/Premonition",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/39/IconPerks_premonition.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 1
    },
    "Prove Thyself": {
        "url": "https://deadbydaylight.fandom.com/wiki/Prove_Thyself",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0f/IconPerks_proveThyself.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 3,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Quick & Quiet": {
        "url": "https://deadbydaylight.fandom.com/wiki/Quick_%26_Quiet",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPerks_quickAndQuiet.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 2,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 4
    },
    "Red Herring": {
        "url": "https://deadbydaylight.fandom.com/wiki/Red_Herring",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/1c/IconPerks_redHerring.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 2
    },
    "Repressed Alliance": {
        "url": "https://deadbydaylight.fandom.com/wiki/Repressed_Alliance",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/31/IconPerks_repressedAlliance.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 4
    },
    "Resilience": {
        "url": "https://deadbydaylight.fandom.com/wiki/Resilience",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/ee/IconPerks_resilience.png",
        "Cleansing": 1,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 1,
        "Looting": 1,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 6
    },
    "Resurgence": {
        "url": "https://deadbydaylight.fandom.com/wiki/Resurgence",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/f3/IconPerks_resurgence.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 3
    },
    "Rookie Spirit": {
        "url": "https://deadbydaylight.fandom.com/wiki/Rookie_Spirit",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2f/IconPerks_rookieSpirit.png",
        "Cleansing": 0,
        "Informative": 2,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Saboteur": {
        "url": "https://deadbydaylight.fandom.com/wiki/Saboteur",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0e/IconPerks_saboteur.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 6
    },
    "Renewal": {
        "url": "https://deadbydaylight.fandom.com/wiki/Renewal",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPerks_renewal.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 2,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Self-Care": {
        "url": "https://deadbydaylight.fandom.com/wiki/Self-Care",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b2/IconPerks_self-Care.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Self-Preservation": {
        "url": "https://deadbydaylight.fandom.com/wiki/Self-Preservation",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/43/IconPerks_self-Preservation.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 2,
        "Clutch": 1,
        "Total": 4
    },
    "Slippery Meat": {
        "url": "https://deadbydaylight.fandom.com/wiki/Slippery_Meat",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/03/IconPerks_slipperyMeat.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 4
    },
    "Small Game": {
        "url": "https://deadbydaylight.fandom.com/wiki/Small_Game",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/dc/IconPerks_smallGame.png",
        "Cleansing": 3,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 5
    },
    "Smash Hit": {
        "url": "https://deadbydaylight.fandom.com/wiki/Smash_Hit",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e0/IconPerks_smashHit.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 2,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 2
    },
    "Sole Survivor": {
        "url": "https://deadbydaylight.fandom.com/wiki/Sole_Survivor",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8e/IconPerks_soleSurvivor.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 1,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 3
    },
    "Solidarity": {
        "url": "https://deadbydaylight.fandom.com/wiki/Solidarity",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPerks_solidarity.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 2,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 5
    },
    "Soul Guard": {
        "url": "https://deadbydaylight.fandom.com/wiki/Soul_Guard",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a5/IconPerks_soulGuard.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 5
    },
    "Spine Chill": {
        "url": "https://deadbydaylight.fandom.com/wiki/Spine_Chill",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/57/IconPerks_spineChill.png",
        "Cleansing": 1,
        "Informative": 2,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 1,
        "Looting": 1,
        "Looping": 1,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 0,
        "Total": 8
    },
    "Sprint Burst": {
        "url": "https://deadbydaylight.fandom.com/wiki/Sprint_Burst",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e4/IconPerks_sprintBurst.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 3
    },
    "Stake Out": {
        "url": "https://deadbydaylight.fandom.com/wiki/Stake_Out",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/cd/IconPerks_stakeOut.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 2
    },
    "Streetwise": {
        "url": "https://deadbydaylight.fandom.com/wiki/Streetwise",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/ff/IconPerks_streetwise.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Technician": {
        "url": "https://deadbydaylight.fandom.com/wiki/Technician",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/6/62/IconPerks_technician.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 3
    },
    "Tenacity": {
        "url": "https://deadbydaylight.fandom.com/wiki/Tenacity",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9d/IconPerks_tenacity.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 2,
        "Total": 3
    },
    "This Is Not Happening": {
        "url": "https://deadbydaylight.fandom.com/wiki/This_Is_Not_Happening",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/58/IconPerks_thisIsNotHappening.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 3
    },
    "Up the Ante": {
        "url": "https://deadbydaylight.fandom.com/wiki/Up_the_Ante",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a3/IconPerks_upTheAnte.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 2
    },
    "Unbreakable": {
        "url": "https://deadbydaylight.fandom.com/wiki/Unbreakable",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4a/IconPerks_unbreakable.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 3,
        "Total": 5
    },
    "Urban Evasion": {
        "url": "https://deadbydaylight.fandom.com/wiki/Urban_Evasion",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c7/IconPerks_urbanEvasion.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 2,
        "Clutch": 0,
        "Total": 2
    },
    "Vigil": {
        "url": "https://deadbydaylight.fandom.com/wiki/Vigil",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/46/IconPerks_vigil.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 2,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 5
    },
    "Visionary": {
        "url": "https://deadbydaylight.fandom.com/wiki/Visionary",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7c/IconPerks_visionary.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 1,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 4
    },
    "Wake Up!": {
        "url": "https://deadbydaylight.fandom.com/wiki/Wake_Up!",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/f/fd/IconPerks_wakeUp.png",
        "Cleansing": 0,
        "Informative": 1,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 3
    },
    "We'll Make It": {
        "url": "https://deadbydaylight.fandom.com/wiki/We%27ll_Make_It",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/8a/IconPerks_wellMakeIt.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 3,
        "Repairing": 0,
        "Healing": 3,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 7
    },
    "We're Gonna Live Forever": {
        "url": "https://deadbydaylight.fandom.com/wiki/We%27re_Gonna_Live_Forever",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b8/IconPerks_wereGonnaLiveForever.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 1,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 5
    },
    "Windows of Opportunity": {
        "url": "https://deadbydaylight.fandom.com/wiki/Windows_of_Opportunity",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/17/IconPerks_windowsOfOpportunity.png",
        "Cleansing": 0,
        "Informative": 3,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 0,
        "Total": 6
    },
    "Overcome": {
        "url": "https://deadbydaylight.fandom.com/wiki/Overcome",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/82/IconPerks_overcome.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 0,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 3,
        "Self-Sufficient": 0,
        "Stealth": 0,
        "Clutch": 1,
        "Total": 4
    },
    "Corrective Action": {
        "url": "https://deadbydaylight.fandom.com/wiki/Corrective_Action",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4f/IconPerks_correctiveAction.png",
        "Cleansing": 0,
        "Informative": 0,
        "Team-Oriented": 2,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 0,
        "Stealth": 1,
        "Clutch": 1,
        "Total": 4
    },
    "Boon: Exponential": {
        "url": "https://deadbydaylight.fandom.com/wiki/Boon:_Exponential",
        "img_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/76/IconPerks_boonExponential.png",
        "Cleansing": 2,
        "Informative": 0,
        "Team-Oriented": 1,
        "Repairing": 0,
        "Healing": 0,
        "Looting": 0,
        "Looping": 0,
        "Self-Sufficient": 3,
        "Stealth": 0,
        "Clutch": 2,
        "Total": 8
    }
}

/*
for (let perk in survivor_perks) {
    // preload all images
    var img = new Image();
    img.src = survivor_perks[perk].img_url;
}
*/